export const GET_USERS = "GET_USERS"
export const CREATE_USERS = "CREATE_USERS"
export const CHANGE_INFORMATION = "CHANGE_INFORMATION"
export const CHANGE_INFORMATION_SUCCESS = "CHANGE_INFORMATION_SUCCESS"